#!/bin/sh

BASEDIR=$(dirname $(realpath $0))

USER=$(whoami)

if [ "$USER" != "root" ]; then
	ARGS="--bind=$BASEDIR:/mnt --bind-ro=/etc/passwd --user=$USER --chdir=/mnt"
fi

exec sudo systemd-nspawn --directory=$BASEDIR/_ptxdist $ARGS  $@
