#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

USER=$(whoami)


exec sudo systemd-nspawn --directory=$BASEDIR/_ptxdist --bind-ro=/etc/passwd --bind=$BASEDIR:/mnt --chdir=/mnt --user=$USER  $@
