#!/usr/bin/python -Bu

# Copyright (c) 2022 Artur Wiebe <artur@4wiebe.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


import pathlib, socket
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler
from systemd import daemon
from shared import log



class updateHttpHandler(BaseHTTPRequestHandler):
	def log_error(self, format, *args):
		log.error(format%args)
	def log_request(self, code='-', size='-'):
		log.info(f'HTTP request for: {self.name} / response: {code}')
	
	def do_GET(self):
		self.name    = self.path.strip('/')
		project = pathlib.Path('/usr/lib/esp32', self.name)
		
		if not project.exists():
			self.send_error(HTTPStatus.NOT_FOUND, message='esp32 project "{self.name}" not found')
			self.end_headers()
			return
		
		if pathlib.Path(project, 'app.hash').read_text().startswith(str(self.headers.get('Hash'))):
			self.send_response(HTTPStatus.NOT_MODIFIED)
			self.end_headers()
			return
		
		binary = pathlib.Path(project, 'app.bin').read_bytes()
		
		self.send_response(HTTPStatus.OK)
		self.send_header("Content-Length", str(len(binary)))
		self.end_headers()
		self.wfile.write(binary)



systemdSocket = socket.fromfd(daemon.LISTEN_FDS_START, socket.AF_INET6, socket.SOCK_STREAM)
updateHttpHandler(systemdSocket, systemdSocket.getpeername(), None) #type:ignore
