#!/usr/bin/python -Bu

# Copyright (c) 2023 Artur Wiebe <artur@4wiebe.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


import logging
from argparse import ArgumentParser
from pathlib import Path
from shared import system


parser = ArgumentParser()
parser.add_argument(
	"name",
	help="irq device name"
)
parser.add_argument(
	"--priority",
	help="priority (80)",
	default='80'
)
parser.add_argument(
	"--affinity",
	help="affinity (1)",
	default='1'
)
args = parser.parse_args()


procs = system.run(['pgrep','-l', f'irq/[0-9]*-{args.name}'], True, text=True).rstrip().split('\n')
#print(procs)

for proc in procs:
	proc = proc.split()
	
	logging.info(f'Setting rt-priority {args.priority} and cpu affinity {args.affinity} for {proc[1]}')

	#set priority
	pid = proc[0]
	system.run(['chrt','-fp', args.priority, pid])

	#set affinity
	irq = proc[1].lstrip('irq/').partition('-')[0]
	Path('/proc/irq', irq, 'smp_affinity_list').write_text(args.affinity)
