#!/bin/sh

cd "$(dirname "$(realpath "$0")")/.."

. ptxdist/config


exec podman build \
	--tag=ptxdist-$PTXDIST_VERSION \
	--build-arg PTXDIST_VERSION=$PTXDIST_VERSION \
	--build-arg OSELAS_VERSION=$OSELAS_VERSION \
	ptxdist
