#!/bin/sh

cd "$(dirname "$(realpath "$0")")/.."

. ptxdist/config


cat ptxdist/Containerfile.d/* | \
podman build \
	--tag=ptxdist-$PTXDIST_VERSION \
	--build-arg-file=ptxdist/config \
	-f - \
	ptxdist
