#!/bin/sh

cd "$(dirname "$(realpath "$0")")/.."

. ptxdist/config

IMAGE=ptxdist-$PTXDIST_VERSION
HOMEDIR=/home/dev
WORKDIR="$HOMEDIR/$(basename "$PWD")"

[ -L keys ] \
	&& BIND_KEYS="$(realpath keys)"


exec podman run \
	--rm \
	--tty \
	--interactive \
	--userns=keep-id:uid=1000,gid=1000 \
	"--volume=$IMAGE-src:$HOMEDIR/src" \
	"--volume=$IMAGE-cache:$HOMEDIR/.cache" \
	"--volume=$PWD:$WORKDIR" \
	${BIND_KEYS:+"--volume=$BIND_KEYS:$BIND_KEYS"} \
	"--workdir=$WORKDIR" \
	--hostname=${IMAGE//./-} \
	--name=$IMAGE \
	$IMAGE \
	"$@"
