#!/usr/bin/python -Bu

from pathlib import Path
from shared.setup import setup
from shared import system
from shared import log



application = setup['codesys']['application']

if system.virtual():
	application = setup['codesys']['sim']['application'] or application

if application:
	log.info(f'Selected CODESYS application: {application}')
	link = Path('/run/codesys/Application')
	link.unlink(True)
	link.symlink_to(f'/opt/codesys/PlcLogic/{application}')
