#!/usr/bin/python -Bu

import server

import system
import state

import log
import issue
import network
import update
import remote
import backup

import app


server.addDocument('',		'gui.html')


server.run()
