#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

PLATFORMS='base/configs/i586/platformconfig base/configs/i686/platformconfig base/configs/iMX6/platformconfig'

cd $BASEDIR


errexit() {
	echo "#############################################"
	echo "Build failed!"
	echo "$1"
	exit 1
}


for P in $PLATFORMS
do
	ptxdist --platformconfig=$P -q clean				|| errexit "Error while cleaning $P"
done

for P in $PLATFORMS
do
	ptxdist --platformconfig=$P -j go					|| errexit "Error while building $P"
done


echo "#############################################"
echo "Build completed successfully!"

exit 0
