SYSTEMD_VERSION		:= 253.5
SYSTEMD_MD5		:= c7f2b9587bc772a0cc211cac3477ed20


SYSTEMD			:= systemd-$(SYSTEMD_VERSION)
SYSTEMD_URL		:= https://github.com/systemd/systemd-stable/archive/v$(SYSTEMD_VERSION).$(SYSTEMD_SUFFIX)
SYSTEMD_SOURCE		:= $(SRCDIR)/$(SYSTEMD).$(SYSTEMD_SUFFIX)
SYSTEMD_DIR		:= $(BUILDDIR)/$(SYSTEMD)
