#!/bin/sh

FILE="$1"

cd "$(dirname "$(realpath "$0")")/.."


OUTPUT="$(dirname "$FILE")/$(basename --suffix=.gpg "$FILE").txz"

gpg --homedir=keys --decrypt --batch --no-permission-warning --passphrase="" --output="$OUTPUT" "$FILE"
