#!/bin/sh

BASEDIR=$(dirname $(realpath $0))
cd $BASEDIR/..


FILE="$1"
HOST=${2-sys}

SSH="ssh -i keys/id_rsa root@$HOST"

gpg --homedir=keys --decrypt --no-permission-warning "$FILE" | $SSH "tar -xJ -C/ etc/app  && reboot"
