#!/bin/sh

BASEDIR=$(dirname $(realpath $0))
cd $BASEDIR/..


FILE="$1"

output() {
	echo $(dirname "$FILE")/$(basename --suffix=.gpg "$FILE").txz
}

gpg --homedir=keys --decrypt --batch --no-permission-warning --passphrase="" --output="$(output)" "$FILE"
