#!/bin/sh

HOST=${1-controlOS}

SSHFSMNT=/tmp/sys-fs


BASEDIR=$(dirname $(realpath $0))
cd $BASEDIR/..



mkdir -p $SSHFSMNT


sshfs \
	-o IdentityFile=$BASEDIR/../keys/id_rsa \
	root@$HOST:/ \
	$SSHFSMNT

ssh \
	-i keys/id_rsa \
	root@$HOST


fusermount3 -u $SSHFSMNT
