#!/bin/sh

# SPDX-FileCopyrightText: 2025 Artur Wiebe <artur@4wiebe.de>
# SPDX-License-Identifier: MIT


HOST=${1-controlOS}


BASEDIR=$(dirname "$(realpath "$0")")
cd $BASEDIR/..


SSHCMD="ssh -t -i keys/id_rsa"
SSHUSER="root@$HOST"

do_ssh() {
	echo "ssh $@"
	$SSHCMD $SSHUSER $@  || exit 1
}

do_rsync() {
	echo "rsync $@"
	[ -n "$(rsync -rltpE -i -e "$SSHCMD" $1 $SSHUSER:$2)" ]
}


do_ssh "mount --options=remount,rw --target=/mnt/root"

do_rsync code/shared /mnt/root/usr/lib/python3.13/site-packages


do_rsync code/app /mnt/root/usr/lib \
	&& do_ssh "systemctl --quiet restart app.service" \
	&

do_rsync code/gui /mnt/root/usr/lib \
	&& do_ssh "systemctl --quiet stop gui-*.service" \
	&

wait
