#!/bin/sh

HOST=${1-controlOS}

BASEDIR=$(dirname $(realpath $0))
cd $BASEDIR/..


SSHCMD="ssh -t -i keys/id_rsa"
SSHUSER="root@$HOST"

sshsys() {
	$SSHCMD $SSHUSER $@							|| exit 1
}

rsyncsys() {
	rsync -rl -tp -v -e "$SSHCMD" $1 $SSHUSER:$2		|| exit 1
}


sshsys "mount --options=remount,rw --target=/mnt/root"

rsyncsys root/projectroot/usr/lib/gui /mnt/root/usr/lib

sshsys "systemctl --quiet stop gui-*.service"
