#!/bin/sh

HOST=${1-sys}
PORT=${2-22}

SSHFSMNT=/tmp/sys-fs


SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

cd $BASEDIR



mkdir -p $SSHFSMNT


if [ "$HOST" = "sys" ]; then

  sshfs \
    -p $PORT \
    -o IdentityFile=$BASEDIR/ssh/id_rsa \
    root@$HOST:/ \
    $SSHFSMNT

  ssh \
    -i ssh/id_rsa \
    -p $PORT \
    root@$HOST

else

  ssh \
    -i ssh/id_rsa \
    -p $PORT \
    -C \
    -o Tunnel=ethernet \
    -w 0 \
    root@$HOST

fi


fusermount3 -u $SSHFSMNT
