#!/bin/sh

HOST=${1-controlOS}

BASEDIR=$(dirname $(realpath $0))
cd $BASEDIR/..

SSHCMD="ssh -t -i keys/ssh/id_rsa root@$HOST"

PLATFORM=$($SSHCMD "grep PTXDIST_PLATFORM_NAME /etc/os-release")
PLATFORM=${PLATFORM#*\"}
PLATFORM=${PLATFORM%\"*}
echo "Platform: $PLATFORM"

pv root/platform-$PLATFORM/images/update | $SSHCMD "update --bare"
