#!/bin/sh

HOST=${1-sys}

SCRIPT=$(realpath $0)
BASEDIR=$(dirname $SCRIPT)

cd $BASEDIR/..


SSH="ssh -i keys/ssh/id_rsa root@$HOST"


pv images/update | $SSH "cat > /mnt/init/..update && mv /mnt/init/..update /mnt/init/update && reboot"
